### ISSUE TITLE
Display alignment - Minor

### ISSUE THREAD

**Issue by Nailsmith** [astropcr/pmasecapstone#11]
The numbers that populate the environment selection boxes are not centered.  They sit too low in the box.
![image](https://cloud.githubusercontent.com/assets/20606189/17078142/82cff6aa-50b0-11e6-83a0-51de98477e78.png)

**Comment by fuzzynickel** [comment]
Fixed in commit id b04c75ce433962359a804c1a668f597a05c6677d

Text is now centered (green boxen are a little bit bigger).

Tooltips are also a little larger to enhance readability
