### ISSUE TITLE
Log file needs to be cleared or new one created for each instance

### ISSUE THREAD

**Issue by fuzzynickel** [astropcr/pmasecapstone#12]
The log file is growing rather unwieldy and could potentially consume a hard drive.  Possible solutions:
1. enable a verbosity setting option [hard]
2. use the same log file but clear it each time [easy]
3. generate a new log file for each 'run' of the application [easy but puts work on the user to clear the log files]

**Comment by astropcr** [comment]
I will configure it to never get larger than 5 megabytes.

**Comment by astropcr** [comment]
Fix should pushed to re-make the log file at 5 MB. It'll also fill up a lot slower when I turn down the logging level after we are done testing. Right now it is on TRACE level so every little thing is logging.
