### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by rkeller6** [astropcr/pmasecapstone#2]
Did not open the word doc or save it to the results file

[disasterTradeStudyLog_K_1.txt](https://github.com/astropcr/pmasecapstone/files/379136/disasterTradeStudyLog_K_1.txt)

**Comment by astropcr** [comment]
Did you press the calculate button multiple times? Trying to understand the log statement.

**Comment by rkeller6** [comment]
Hit it once, then waited, checked the results folder with no luck.

Pressed it several more times (like a monkey... but not a code monkey) with
similar results.

**Comment by astropcr** [comment]
Did you try to run it off the DropBox folder or did you copy it to your main hard drive?

**Comment by rkeller6** [comment]
It was run off a folder on my desktop.

**Comment by mrozbarrett** [comment]
Having the same (or similar) issue.  Text below is from log file:

[DEBUG] 2016-07-22T18:59:35,165 edu.gatech.pmase.capstone.awesome.impl.DRTSSanityFilter selectFinalArchitecture - Architecture Result: DRTSArchitectureResult{platform=Medium UAV, sensor=X-Band SAR, comms=Satellite VGC} filtered out.
[INFO] 2016-07-22T18:59:35,165 edu.gatech.pmase.capstone.awesome.impl.DRTSSanityFilter selectFinalArchitecture - Found final architecture result 2 : DRTSArchitectureResult{platform=Heavy UAV, sensor=X-Band SAR, comms=Satellite VGC}
[INFO] 2016-07-22T18:59:35,166 edu.gatech.pmase.capstone.awesome.impl.DRTSSanityFilter selectFinalArchitecture - Found final architecture result 3 : DRTSArchitectureResult{platform=Light Rotary, sensor=X-Band SAR, comms=Satellite VGC}
[DEBUG] 2016-07-22T18:59:35,166 edu.gatech.pmase.capstone.awesome.impl.DRTSSanityFilter selectFinalArchitecture - Filtered out 13 architecture selections before finding 3
[INFO] 2016-07-22T18:59:35,166 edu.gatech.pmase.capstone.awesome.impl.DisasterResponseTradeStudySingleton calculate - 3 final results returned
[INFO] 2016-07-22T18:59:35,167 edu.gatech.pmase.capstone.awesome.impl.DisasterResponseTradeStudySingleton calculate - Final Architecture Selected with a score of: 2.0: DRTSArchitectureResult{platform=Heavy Fixed Wing, sensor=X-Band SAR, comms=Satellite VGC}
[INFO] 2016-07-22T18:59:35,167 edu.gatech.pmase.capstone.awesome.impl.DisasterResponseTradeStudyOutputer createOutputFile - Creating results architecture file.
[DEBUG] 2016-07-22T18:59:35,168 edu.gatech.pmase.capstone.awesome.impl.DisasterResponseTradeStudyOutputer createOutputFile - Using results template file: C:\Users\Kathleen\Documents\Disaster-Response-Trade-Study-Tool\results\template.docx

**Comment by mrozbarrett** [comment]
Used executable (but didn't ask for admin privileges) here's the log file, still did not get an output
[disasterTradeStudy.txt](https://github.com/astropcr/pmasecapstone/files/379347/disasterTradeStudy.txt)

**Comment by mrozbarrett** [comment]
This is using 0.5.1 - still no output file but did get additional information in the log file when it was trying to create report.  See attached.  
[disasterTradeStudy.txt](https://github.com/astropcr/pmasecapstone/files/379364/disasterTradeStudy.txt)

**Comment by astropcr** [comment]
I believe the bug Katie reported in v0.5.1 should be fixed as of v0.5.3. Please try and see if still any issue. Let me know if I can close or if still cropping up.

**Comment by Nailsmith** [comment]
Tried with 5.3 and first time through got good report; ran from my desktop. Tried it again with all the types selected and like we discussed last night got nothing.  Then went all the way down to "Smoke and Dust" only and still nothing.  log file for that one is attached.
[disaster log1.txt](https://github.com/astropcr/pmasecapstone/files/379775/disaster.log1.txt)

**Comment by Nailsmith** [comment]
Here's one I went through and meticulously made selections for what I think would be very realistic scenario for volcanic area. Tried from my desktop and from my "My Documents" folder and got no
[Log2.txt](https://github.com/astropcr/pmasecapstone/files/379780/Log2.txt)

 WordDoc results.

**Comment by astropcr** [comment]
Nail, your first log had no valid architectures found. Your second one has a real bug I am looking at right now.

**Comment by astropcr** [comment]
The second log had no sane results found, all the architectures were filtered by the Sanity Filter. Fixed the bug that made the exception though (I initially assumed that at least one architecture would come out of SanityFilter).

**Comment by mrozbarrett** [comment]
Problem is now fixed.  Yay!!!!!!!!!!

**Comment by astropcr** [comment]
Going to close this. Please let me know if it pops up again.

**Comment by astropcr** [comment]
Actually fixed in commit bd9df2d3cb6520cab084b50141b99b52f5bd6889
