### ISSUE TITLE
Sensor Filtering Bug

### ISSUE THREAD

**Issue by rkeller6** [astropcr/pmasecapstone#25]
Sensor choice is noon-optimal.

Removed all platform/terrain/disaster filters.  Is selecting SWIR (worse swath, worse GSD, Worse cost, wrost weight)

**Comment by astropcr** [comment]
Need some logs please.

**Comment by astropcr** [comment]
[disasterTradeStudyLog.txt](https://github.com/astropcr/pmasecapstone/files/380387/disasterTradeStudyLog.txt)
[disasterTradeStudyLog-2016-07-24-1.txt](https://github.com/astropcr/pmasecapstone/files/380388/disasterTradeStudyLog-2016-07-24-1.txt)

**Comment by astropcr** [comment]
@rkeller6 , new version (v0.7.0) pushed. Please test with that to see if results are better. Thanks!

**Comment by fuzzynickel** [comment]
@rkeller6 , new version (v0.7.1) pushed.  Please test and see if you get betterer results.  K thnx bai!

**Comment by fuzzynickel** [comment]
Everything has been fixed.  Version 0.7.2 is now released and out on DropBox.
