### ISSUE TITLE
Spelling of Ground Instability on Disaster Effects Slide

### ISSUE THREAD

**Issue by mrozbarrett** [astropcr/pmasecapstone#3]
Change "Gound Instability" to "Ground Instability" on Disaster Effects Slide.

**Comment by astropcr** [comment]
On the slide?

**Comment by fuzzynickel** [comment]
Fixed in commit e0cd0dcbf001e25059d6a603e42b171925c9eb83

**Comment by fuzzynickel** [comment]
"Ground" is still misspelled as "Gound"
