### ISSUE TITLE
When everything gets filtered then no output...

### ISSUE THREAD

**Issue by rkeller6** [astropcr/pmasecapstone#5]
[disasterTradeStudyLog_K.txt](https://github.com/astropcr/pmasecapstone/files/379311/disasterTradeStudyLog_K.txt)

**Comment by astropcr** [comment]
So what would we want then? A result file with nothing in it?

**Comment by mrozbarrett** [comment]
A pop-up window that states no results were returned based on no viable solutions exist?

**Comment by astropcr** [comment]
Closed because decided to do the Report with the No Option set instead.
