### ISSUE TITLE
Options for Elevation screen in Define Environments

### ISSUE THREAD

**Issue by mrozbarrett** [astropcr/pmasecapstone#7]
The buttons in the elevation window do not show all the text for each option.  See image below for example.  

![image](https://cloud.githubusercontent.com/assets/20606307/17075013/db406204-503b-11e6-9cd5-bc279a61fd67.png)

**Comment by mrozbarrett** [comment]
Same issue exists for the following environments: foliage, wetness, range, and persistence,

**Comment by astropcr** [comment]
Fixed in v0.5.2
