### ISSUE TITLE
Spelling of Persistence

### ISSUE THREAD

**Issue by mrozbarrett** [astropcr/pmasecapstone#9]
Change "persistance" to "persistence" on main DRTST screen and environments subscreen (shown below). 
![image](https://cloud.githubusercontent.com/assets/20606307/17075052/159ea55e-503d-11e6-8bf0-d3221bba5405.png)

**Comment by fuzzynickel** [comment]
Fixed in commit e0cd0dcbf001e25059d6a603e42b171925c9eb83
